name: publish page

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: 
        name: install and build
        command: |
          npm ci
          npm run build
        working-directory: ./example
      - run: 
        name: publish page
        command: |
          git config user.email "spade5@spade5.name"
          git config user.name "spade5"
          npm run page
        working-directory: ./example