name: publish page

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Build Page
        working-directory: ./example
        run: npm ci
        run: npm run build
        run: gh-pages -d ./dist